### PR TITLE
annotate: annotate missing branches with "~"

### PR DESCRIPTION
**Pull request by blueyed**
Probably it's better to use an ASCII symbol for this though.

TODO:
 - [x] test

### CODE REVIEW

**Comment by nedbat** [comment]
I agree that it should be ascii, and that there should be tests :)

**Comment by nedbat** [comment]
Tilde works as a symbol.

On master I've removed 2.6 and 3.3 support, and deleted the unused tox and CircleCI configurations.  Thanks for the prod.

**Comment by blueyed** [comment]
Changed and added a test.
Not sure if using farm tests is the best way though?!

**Comment by blueyed** [comment]
Moved to https://github.com/nedbat/coveragepy/pull/676.

**Pull request closed without merging**
